sheet_id = "1pqi3T9_y7EwWMB0jliFgIixF8-UXt2Nisrt7GqEtoZk"

[gcp_service_account]
type = "service_account"
project_id = "visontest-470308"
private_key_id = "9cd003878e941469ec9e81a0bbad50c69911d644"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkteXIH4G9w8x/
RA0rIRQvnuO0tn9X0ycVg1U8EWpowTrjEeRSrK/uU1u3KP8n3AbTb45Nws2BtNkx
qVuResx9Je5sdd30V62oVgLNFq1zu9LJ9Ro0jEIGngK/ersrzLXfYsXbt/a1AU2Z
WSwqzgHgJslyCA0v3jotX/L0Z/CwxZiRhQZTfxzepurgbUjjBsMm+rk3lImUe8ED
K5kIihOFgc3rSVo64vPV8gs0UGO6zJJUMQQ52RvL9Yl4ODV8jHTagkPxgejQQWSY
7L70NrPtDB6enHMzlTWAg649ZCl4O1M9HE36iW5BaocZjmEXNoCG2/j9Efq51HbC
rLLvag81AgMBAAECggEABFpaTEOo5h76lJJz1qP1KJ0GX4xDKUsHSWZDJmc/bK1O
pRmf8x9lNuM1FU4cEC2ccJIOLLftPnRNGSbkqJ+aL+SEvJEQ4JhAmqZLRKhIxTo9
g+DaZHEgfZRHdlAEClBKrjCqEfh2qKn0Jw1YQXlYS1g7EqxrzMwOtYxHm3Xzwngr
d/D/vpNf/GaksruTD/QCwD7zfE72a9moxohtWlWSrhGS47VOdmVcD2Py7gAe0Buj
E7HLdWWTZnV4JBtCSg5MVR4uth+vK/W7sZkpxJnEPc1+r00Uie9sxZ5EIYBSai2r
/1mm/1JXfbgOSjIaj7CeghWEikvol+NmTqxm8LWaAQKBgQDlwvGjBeskT01eaRG/
PSEUUuLRtHXAawjOcH7ZoYb5lIjRZQ6aky9xw+RbeZMZKplNiSI71D3A4FERp1cg
OH5ySQMS7kg4JAmVpxww81ezYSWyJdYM0Rwv4gesZxAJy0aPDgnBCVr6u8NW/2Wc
gTUgDo/oqX5BOmsjxXJxl4pzIQKBgQC3hTHh40mwdriSxC0oKnfoI6gz47gZvmzx
XLIV53dsLKYSzSW8Jtc1sRdk8nRzUvEsD4LJsueBWEyVJOv2U+5SeEswYEje1z5c
7+oSLUgdlIMGqeGesksY+azR+4JAaiKPafN1vYwKRnWGFo3BXV53IMrJ/46RUxIW
+BjoftBtlQKBgQDJnPq0dukTf5MAmWo9ScLRNrpaEeSR6Fpd7FEjX541O6WjOO5L
rYQgbCjiLBhsKPlFFGS541AdA7mfqBvH5krutirAXd95hAX1ECKowZ/fhAuz+4eM
z6HQUqMxIW7taTaNKWBdx3vSMRkEKjBb2PVpH94f5zsmucByLzxxeOzAgQKBgE28
5Rlrfv55+8tnwD0gaDR0Tj7UulplWJ6RBnrS1rqC20JhlhdyWH1M67z+GyfyvWhN
lbg8yWX38lDHGBD7EpvqiucOEjAa+zbBBeT3O3IUQ8Bh28muerM0p+k24cDJdKRN
XCzGwvhjSksnaJq9I1PRFzWjxE944dPK+joZ5c5VAoGAL0EzpsKF0wYJGnTK0eLu
e+Ov9n4MjwUmfYxMhzw61dFuSQ79PGeZE4od6SFQTE7jdrij2XYv6T2ZKyqtTL2J
Z2EJFBJ3wEhB80/vk+3cZ9XEcfmsB+dC83j6vOtSbZP1oF4bP8MkXHnaai6zLmek
MHUlvjezCe3VNnqX+f6fSz0=
-----END PRIVATE KEY-----"""

client_email = "vision-test-account@visontest-470308.iam.gserviceaccount.com"
client_id = "111962096562429722488"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vision-test-account%40visontest-470308.iam.gserviceaccount.com"


